import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Torrent = { id:number; hashString:string; name:string; status:number; percentDone:number; rateDownload:number; rateUpload:number; eta:number };
type PrinterStatus = { configured:boolean; online:boolean; host:string; adminUrl:string; detectedPorts:number[]; protocol:string; note:string };
type NetworkStatus = { id:string; name:string; kind:string; online:boolean; ip:string; mac:string; latencyMs:number; adminUrl:string; note:string };
type CopyState = { torrentName:string; destination:string; state:string; message?:string; attempts?:number; copiedBytes?:number; totalBytes?:number; currentFile?:string; fileCopiedBytes?:number; fileTotalBytes?:number; speedBytesPerSec?:number; etaSeconds?:number; percent?:number };
type TuyaPoint = { code:string; value:unknown };
type TuyaSpec = { code:string; type:string; values:string; dp_id?:number; dpId?:number };
type TuyaDevice = { id:string; name:string; online:boolean; category:string; productName:string; productId?:string; status:TuyaPoint[]; functions:TuyaSpec[]; statusSpec:TuyaSpec[] };
type TuyaScene = { id:string; name:string; capabilities:Array<{interface_name?:string;commands?:string[]}> };
type SmartHome = { configured:boolean; online:boolean; lastUpdatedAt:string|null; error?:string; devices:TuyaDevice[]; scenes:TuyaScene[] };
type State = {
  snapshot: null | { timestamp:string; kd20:{online:boolean;torrents:Torrent[]}; wd:{online:boolean;freeBytes:number;totalBytes:number;mediaRoot:string}; printer?:PrinterStatus; network?:NetworkStatus[] };
  bridgeLastSeenAt:string|null; bridgeOnline:boolean; settings:{autoCopyEnabled:boolean;autoCopyDestination:string}; copies:Record<string,CopyState>;
  recentCommands:Array<{id:string;type:string;createdAt:string;completedAt?:string;ok?:boolean;message?:string}>; smartHome:SmartHome;
};

const fmtBytes=(n:number)=>{ if(!n)return"0 B"; const u=["B","KB","MB","GB","TB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i>2?2:1)} ${u[i]}`};
const fmtSpeed=(n:number)=>`${fmtBytes(n)}/s`;
const fmtTime=(v?:string|null)=>v?new Date(v).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const fmtDuration=(s?:number)=>!s||s<=0?"—":s<60?`${Math.ceil(s)} mp`:s<3600?`${Math.ceil(s/60)} perc`:`${Math.floor(s/3600)} ó ${Math.ceil((s%3600)/60)} p`;
const statusMap=(d:TuyaDevice)=>Object.fromEntries(d.status.map(x=>[x.code,x.value]));
const findPoint=(d:TuyaDevice, patterns:string[])=>d.status.find(x=>patterns.some(p=>x.code.toLowerCase().includes(p)))?.value;
const findCode=(d:TuyaDevice, patterns:string[], type?:string)=>d.functions.find(x=>(!type||x.type.toLowerCase()===type.toLowerCase())&&patterns.some(p=>x.code.toLowerCase().includes(p)))?.code || d.status.find(x=>patterns.some(p=>x.code.toLowerCase().includes(p)))?.code;
function specValues(d:TuyaDevice,code:string){ const x=[...d.functions,...d.statusSpec].find(s=>s.code===code); if(!x)return{} as any; try{return JSON.parse(x.values||"{}")}catch{return{} as any} }
function scaled(d:TuyaDevice, codePatterns:string[], fallback="—") { const p=d.status.find(x=>codePatterns.some(k=>x.code.toLowerCase().includes(k))); if(!p||typeof p.value!=="number")return fallback; const meta=specValues(d,p.code); const scale=Number(meta.scale||0); const v=p.value/Math.pow(10,scale); const unit=String(meta.unit||""); return `${v.toFixed(scale>0?Math.min(scale,1):0)}${unit?` ${unit}`:""}`; }
function deviceKind(d:TuyaDevice){ const s=`${d.name} ${d.productName} ${d.category}`.toLowerCase(); if(/air conditioner|空调|klíma|climate/.test(s))return"climate"; if(/temperature|humidity|hőmér|sensor/.test(s))return"sensor"; if(/gate|kapu|garage|garázs|lock/.test(s))return"gate"; if(/plug|socket|switch|lámpa|lamp/.test(s))return"switch"; return"device"; }
function isDangerous(name:string){return/kapu|gate|garage|garázs|door|lock|zár/i.test(name)}

async function api(path:string,init?:RequestInit){const r=await fetch(path,init);if(r.status===401)throw new Error("AUTH_REQUIRED");const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);return b}

function Login({onDone}:{onDone:()=>void}){const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});onDone()}catch(err){setError(err instanceof Error&&err.message==="too_many_attempts"?"Túl sok sikertelen próbálkozás. Próbáld később.":"Hibás jelszó.")}finally{setBusy(false)}}return <main className="loginShell"><section className="loginCard"><div className="brandMark">H</div><div className="eyebrow">HOME HUB</div><h1>Belépés</h1><p>NAS, hálózat és okosotthon egyetlen felületen.</p><form onSubmit={submit}><input type="password" autoFocus autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="HomeHub jelszó"/><button disabled={busy||!password}>{busy?"Belépés…":"Belépés"}</button></form>{error&&<div className="loginError">{error}</div>}</section></main>}

function SmartDeviceCard({device,onCommand}:{device:TuyaDevice;onCommand:(d:TuyaDevice,code:string,value:unknown)=>void}){
  const kind=deviceKind(device); const sm=statusMap(device);
  const switchCode=findCode(device,["switch"],"Boolean"); const switchValue=switchCode?Boolean(sm[switchCode]):undefined;
  const temp=scaled(device,["temp_current","va_temperature","temperature","temp_value","temp"]);
  const hum=scaled(device,["humidity","va_humidity","humid"]);
  const batt=findPoint(device,["battery_percentage","battery_value","battery"]);
  const setTempCode=findCode(device,["temp_set","target_temp","temp_target"]);
  const modeCode=findCode(device,["mode"],"Enum"); const modeMeta=modeCode?specValues(device,modeCode):{}; const modes=Array.isArray(modeMeta.range)?modeMeta.range:[];
  const [target,setTarget]=useState(()=>{ if(!setTempCode)return""; const v=sm[setTempCode]; const meta=specValues(device,setTempCode); const scale=Number(meta.scale||0); return typeof v==="number"?String(v/Math.pow(10,scale)):"" });
  return <article className={`smartDevice ${kind}`}>
    <div className="deviceHead"><div><span className={`deviceDot ${device.online?"on":""}`}></span><strong>{device.name}</strong></div><span className="deviceKind">{kind==="climate"?"Klíma":kind==="sensor"?"Szenzor":kind==="switch"?"Kapcsoló":kind==="gate"?"Kapu":"Eszköz"}</span></div>
    <small>{device.productName||device.category} · {device.online?"Online":"Offline"}</small>
    <div className="metrics">{temp!=="—"&&<span>🌡 {temp}</span>}{hum!=="—"&&<span>💧 {hum}</span>}{typeof batt==="number"&&<span>🔋 {batt}%</span>}</div>
    <div className="deviceControls">
      {switchCode&&<button className={switchValue?"power on":"power"} disabled={!device.online} onClick={()=>{if(isDangerous(device.name)&&!window.confirm(`${device.name}: biztosan végrehajtod?`))return;onCommand(device,switchCode,!switchValue)}}>{switchValue?"Bekapcsolva":"Kikapcsolva"}</button>}
      {setTempCode&&<div className="tempControl"><input type="number" step="0.5" value={target} onChange={e=>setTarget(e.target.value)}/><button onClick={()=>{const meta=specValues(device,setTempCode);const scale=Number(meta.scale||0);onCommand(device,setTempCode,Math.round(Number(target)*Math.pow(10,scale)))}}>°C beállítás</button></div>}
      {modeCode&&modes.length>0&&<select value={String(sm[modeCode]??"")} onChange={e=>onCommand(device,modeCode,e.target.value)}>{modes.map((m:string)=><option value={m} key={m}>{m}</option>)}</select>}
    </div>
  </article>
}

function App(){
  const[auth,setAuth]=useState<"checking"|"yes"|"no">("checking");const[state,setState]=useState<State|null>(null);const[magnet,setMagnet]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  async function checkAuth(){const r=await fetch("/api/auth/status");const j=await r.json();setAuth(j.authenticated?"yes":"no")}
  async function load(){try{setState(await api("/api/state"));setAuth("yes")}catch(err){if(err instanceof Error&&err.message==="AUTH_REQUIRED")setAuth("no")}}
  useEffect(()=>{checkAuth();if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
  useEffect(()=>{if(auth!=="yes")return;load();const id=setInterval(load,2000);return()=>clearInterval(id)},[auth]);
  const torrents=state?.snapshot?.kd20.torrents||[];const printer=state?.snapshot?.printer;const network=state?.snapshot?.network||[];const smart=state?.smartHome;
  const totalDl=useMemo(()=>torrents.reduce((a,t)=>a+t.rateDownload,0),[torrents]);const totalUl=useMemo(()=>torrents.reduce((a,t)=>a+t.rateUpload,0),[torrents]);const wdUsed=state?.snapshot?.wd.totalBytes?1-state.snapshot.wd.freeBytes/state.snapshot.wd.totalBytes:0;
  function flash(m:string){setNotice(m);window.setTimeout(()=>setNotice(""),3500)}
  async function addMagnet(e:React.FormEvent){e.preventDefault();if(!magnet.trim())return;setBusy(true);try{await api("/api/torrents/magnet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({magnet})});setMagnet("");flash("Magnet link elküldve a KD20-nak.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}finally{setBusy(false);load()}}
  async function addFile(file?:File){if(!file)return;const fd=new FormData();fd.append("torrent",file);setBusy(true);try{await api("/api/torrents/file",{method:"POST",body:fd});flash(".torrent fájl elküldve a KD20-nak.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}finally{setBusy(false);load()}}
  async function copy(t:Torrent){try{await api(`/api/torrents/${t.id}/copy`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});flash("Másolási feladat elküldve.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}load()}
  async function retryCopy(hash:string){try{await api(`/api/copies/${encodeURIComponent(hash)}/retry`,{method:"POST"});flash("Másolás újrapróbálása elküldve.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}load()}
  async function updateSettings(patch:Partial<State["settings"]>){if(!state)return;const next={...state.settings,...patch};try{await api("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});load()}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function smartCommand(d:TuyaDevice,code:string,value:unknown){try{await api(`/api/smart-home/devices/${encodeURIComponent(d.id)}/command`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,value,confirm:isDangerous(d.name)})});flash(`${d.name}: parancs elküldve`);setTimeout(load,900)}catch(err){flash(`Smart Life hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function runScene(s:TuyaScene){const dangerous=isDangerous(s.name);if(dangerous&&!window.confirm(`${s.name}: biztosan elindítod ezt a jelenetet?`))return;try{await api(`/api/smart-home/scenes/${encodeURIComponent(s.id)}/run`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirm:dangerous})});flash(`${s.name}: jelenet elindítva`)}catch(err){flash(`Jelenet hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function refreshSmart(){try{await api("/api/smart-home/refresh",{method:"POST"});load();flash("Smart Life frissítve") }catch(err){flash(`Tuya hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setState(null);setAuth("no")}
  if(auth==="checking")return<main className="splash"><div className="brandMark">H</div><p>HomeHub betöltése…</p></main>;if(auth==="no")return<Login onDone={()=>setAuth("yes")}/>;
  return <main>{notice&&<div className="toast">{notice}</div>}
    <header className="hero"><div><div className="eyebrow">HOME HUB · CORE</div><h1>Otthoni vezérlőközpont</h1><p>NAS, torrent, hálózat, nyomtató és Smart Life egyetlen PWA-ban.</p></div><div className="heroActions"><div className="live"><span className={state?.bridgeOnline?"dot on":"dot"}></span>{state?.bridgeOnline?"Bridge online":"Bridge offline"}</div><button className="ghost" onClick={logout}>Kilépés</button></div></header>

    <section className="cards four"><article className="card"><span>KD20</span><strong>{state?.bridgeOnline&&state?.snapshot?.kd20.online?"Online":"Offline"}</strong><small>{torrents.length} torrent · ↓ {fmtSpeed(totalDl)} · ↑ {fmtSpeed(totalUl)}</small></article><article className="card"><span>WD My Cloud</span><strong>{state?.bridgeOnline&&state?.snapshot?.wd.online?"Online":"Offline"}</strong><small>{state?.snapshot?`${fmtBytes(state.snapshot.wd.freeBytes)} szabad · ${Math.round(wdUsed*100)}% foglalt`:"Nincs adat"}</small></article><article className="card"><span>Hálózat</span><strong>{network.filter(n=>n.online).length}/{network.length||0} online</strong><small>Technicolor + Archer + TP-Link extenderek</small></article><article className="card"><span>Smart Life</span><strong>{smart?.configured?(smart.online?"Online":"Hiba"):"Nincs konfigurálva"}</strong><small>{smart?.devices?.length||0} eszköz · {smart?.scenes?.length||0} jelenet</small></article></section>

    <section className="panel networkPanel"><div className="sectionHead"><div><h2>Otthoni hálózat</h2><p>A WD Bridge helyben ellenőrzi a routereket és Wi-Fi erősítőket. Jelszó nem kerül a Renderre.</p></div></div><div className="networkGrid">{network.map(n=><article className="networkDevice" key={n.id}><div className="deviceHead"><div><span className={`deviceDot ${n.online?"on":""}`}></span><strong>{n.name}</strong></div><span className="deviceKind">{n.kind==="gateway"?"Telekom gateway":n.kind==="router"?"Router":"Wi-Fi erősítő"}</span></div><small>{n.ip||"IP keresése…"}{n.mac?` · ${n.mac}`:""}</small><div className="networkMeta"><span>{n.online?`${n.latencyMs.toFixed(1)} ms`:"Nem elérhető"}</span>{n.adminUrl&&n.ip&&<a href={n.adminUrl} target="_blank" rel="noreferrer">Admin</a>}</div><em>{n.note}</em></article>)}{network.length===0&&<div className="empty">A v0.8 Bridge frissítése után jelennek meg a hálózati eszközök.</div>}</div><div className="infoLine">A pontos Wi-Fi jelerősség és klienslista később kapcsolható be a TP-Link/Technicolor admin API-val; a v0.8 első körben elérhetőséget, IP-t és válaszidőt mér.</div></section>

    <section className="panel smartPanel"><div className="sectionHead"><div><h2>Smart Life</h2><p>Tuya Central Europe Cloud · eszközök és jelenetek dinamikusan a kapcsolt Smart Life fiókból.</p></div><button className="ghost" onClick={refreshSmart}>Frissítés</button></div>{!smart?.configured&&<div className="empty">Renderben add meg a TUYA_ACCESS_ID, TUYA_ACCESS_SECRET és TUYA_API_ENDPOINT változókat.</div>}{smart?.configured&&!smart.online&&<div className="smartError">Tuya kapcsolat: {smart.error||"nem elérhető"}</div>}{smart?.devices?.length>0&&<div className="smartGrid">{smart.devices.map(d=><SmartDeviceCard key={d.id} device={d} onCommand={smartCommand}/>)}</div>}{smart?.scenes?.length>0&&<div className="scenes"><h3>Jelenetek</h3><div className="sceneGrid">{smart.scenes.map(s=><button className={isDangerous(s.name)?"scene danger":"scene"} key={s.id} onClick={()=>runScene(s)}>{s.name}{isDangerous(s.name)&&<small>Megerősítés szükséges</small>}</button>)}</div></div>}</section>

    <section className="panel add"><div><h2>Új torrent</h2><p>Magnet link vagy .torrent fájl.</p></div><form onSubmit={addMagnet} className="magnet"><input value={magnet} onChange={e=>setMagnet(e.target.value)} placeholder="magnet:?xt=urn:btih:…"/><button disabled={busy||!state?.bridgeOnline}>Hozzáadás</button></form><label className={`filebtn ${!state?.bridgeOnline?"disabled":""}`}>.torrent fájl<input disabled={!state?.bridgeOnline} type="file" accept=".torrent,application/x-bittorrent" onChange={e=>addFile(e.target.files?.[0])}/></label></section>

    <section className="panel"><div className="sectionHead"><div><h2>Torrentek</h2><p>A KD20 Transmission aktuális állapota és a WD-re másolás.</p></div><button className="ghost" onClick={load}>Frissítés</button></div><div className="torrentList">{torrents.length===0&&<div className="empty">Még nincs torrent, vagy a Bridge nem küldött adatot.</div>}{torrents.map(t=>{const cp=t.hashString?state?.copies?.[t.hashString]:undefined;const copying=cp&&(cp.state==="queued"||cp.state==="running");const done=cp?.state==="done";const copyPct=Math.max(0,Math.min(100,Math.round((cp?.percent||0)*100)));return <article className="torrent" key={t.hashString||t.id}><div className="torrentTop"><div><strong>{t.name}</strong><span>{Math.round(t.percentDone*100)}%</span></div><div className="copyActions">{cp?.state==="error"&&<button className="retry" onClick={()=>retryCopy(t.hashString)}>Újrapróbálás</button>}<button onClick={()=>copy(t)} disabled={t.percentDone<1||!state?.bridgeOnline||Boolean(copying)||Boolean(done)}>{done?"Átmásolva":copying?"Másolás…":"Másolás WD-re"}</button></div></div><div className="bar"><i style={{width:`${Math.max(1,t.percentDone*100)}%`}}></i></div><small>↓ {fmtSpeed(t.rateDownload)} · ↑ {fmtSpeed(t.rateUpload)} · ID {t.id}</small>{cp&&<div className={`copyState ${cp.state}`}><div className="copyStateLine"><span>Másolás: {cp.state==="queued"?"sorban":cp.state==="running"?"folyamatban":cp.state==="done"?`kész → ${cp.destination}`:`hiba${cp.message?` · ${cp.message}`:""}`}</span>{cp.state==="running"&&<b>{copyPct}%</b>}</div>{cp.state==="running"&&<><div className="copyBar"><i style={{width:`${Math.max(1,copyPct)}%`}}></i></div><div className="copyMeta"><span>{fmtBytes(cp.copiedBytes||0)} / {fmtBytes(cp.totalBytes||0)}</span><span>{fmtSpeed(cp.speedBytesPerSec||0)}</span><span>~ {fmtDuration(cp.etaSeconds)}</span></div>{cp.currentFile&&<div className="copyFile">{cp.currentFile}</div>}</>}</div>}</article>})}</div></section>

    <section className="panel printerPanel"><div><h2>USB nyomtatómegosztás</h2><p>A KD20 USB Print Server funkcióját használjuk.</p></div><div className="printerStatus"><span className={printer?.online?"statusBadge good":"statusBadge"}>{printer?.online?"Nyomtatószolgáltatás elérhető":"Nyomtató még nincs észlelve"}</span><small>{printer?.note||"A Bridge figyeli a nyomtatóportokat."}</small></div><div className="printerActions">{printer?.adminUrl&&<a className="actionLink" href={printer.adminUrl} target="_blank" rel="noreferrer">KD20 Printer Setting</a>}<span>USB → KD20 → Printer Setting → Enable.</span></div></section>
    <section className="panel settings"><div><h2>Automatika</h2><p>A kész torrentet átmásolja, de a KD20-ról nem törli.</p></div><label className="switch"><input type="checkbox" checked={state?.settings.autoCopyEnabled||false} onChange={e=>updateSettings({autoCopyEnabled:e.target.checked})}/><span></span> Automatikus másolás</label><label>Célmappa a WD-n<input value={state?.settings.autoCopyDestination||""} onChange={e=>setState(s=>s?({...s,settings:{...s.settings,autoCopyDestination:e.target.value}}):s)} onBlur={e=>updateSettings({autoCopyDestination:e.target.value})}/></label></section>
  </main>
}
createRoot(document.getElementById("root")!).render(<App/>);
