import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Torrent={id:number;hashString:string;name:string;status:number;percentDone:number;rateDownload:number;rateUpload:number;eta:number};
type PrinterStatus={configured:boolean;online:boolean;host:string;adminUrl:string;detectedPorts:number[];protocol:string;note:string};
type NetworkStatus={id:string;name:string;kind:string;online:boolean;adminOnline?:boolean;ip:string;mac:string;latencyMs:number;adminUrl:string;note:string};
type CopyState={torrentName:string;destination:string;state:string;message?:string;attempts?:number;copiedBytes?:number;totalBytes?:number;currentFile?:string;fileCopiedBytes?:number;fileTotalBytes?:number;speedBytesPerSec?:number;etaSeconds?:number;percent?:number};
type TuyaPoint={code:string;value:unknown};
type TuyaSpec={code:string;type:string;values:string;dp_id?:number;dpId?:number};
type TuyaDevice={id:string;name:string;online:boolean;category:string;productName:string;productId?:string;homeId?:string;status:TuyaPoint[];functions:TuyaSpec[];statusSpec:TuyaSpec[]};
type TuyaScene={id:string;name:string;homeId?:string;enabled?:boolean;capabilities?:Array<{interface_name?:string;commands?:string[]}>};
type SmartHome={configured:boolean;online:boolean;lastUpdatedAt:string|null;error?:string;devices:TuyaDevice[];scenes:TuyaScene[]};
type State={snapshot:null|{timestamp:string;kd20:{online:boolean;torrents:Torrent[]};wd:{online:boolean;freeBytes:number;totalBytes:number;mediaRoot:string};printer?:PrinterStatus;network?:NetworkStatus[]};bridgeLastSeenAt:string|null;bridgeOnline:boolean;settings:{autoCopyEnabled:boolean;autoCopyDestination:string};copies:Record<string,CopyState>;recentCommands:Array<{id:string;type:string;createdAt:string;completedAt?:string;ok?:boolean;message?:string}>;smartHome:SmartHome};

const fmtBytes=(n:number)=>{if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i>2?2:1)} ${u[i]}`};
const fmtSpeed=(n:number)=>`${fmtBytes(n)}/s`;
const fmtDuration=(s?:number)=>!s||s<=0?"—":s<60?`${Math.ceil(s)} mp`:s<3600?`${Math.ceil(s/60)} perc`:`${Math.floor(s/3600)} ó ${Math.ceil((s%3600)/60)} p`;
const bridgeAge=(iso:string|null|undefined)=>{if(!iso)return"Nincs még kapcsolat";const s=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));return s<60?`${s} mp`:`${Math.floor(s/60)} p ${s%60} mp`};
const statusLabel=(status:number)=>({0:"Leállítva",1:"Ellenőrzésre vár",2:"Ellenőrzés",3:"Letöltésre vár",4:"Letölt",5:"Seedre vár",6:"Seedel"}[status]||`Állapot ${status}`);
const isDangerous=(name:string)=>/kapu|gate|garage|garázs|door|lock|zár/i.test(name);
const statusMap=(d:TuyaDevice)=>Object.fromEntries(d.status.map(x=>[x.code,x.value]));
function specFor(d:TuyaDevice,code:string){return[...d.functions,...d.statusSpec].find(s=>s.code===code)}
function specValues(d:TuyaDevice,code:string){const x=specFor(d,code);if(!x)return{} as any;try{return JSON.parse(x.values||"{}")}catch{return{} as any}}
function findFunction(d:TuyaDevice,patterns:string[],type?:string){return d.functions.find(x=>(!type||x.type.toLowerCase()===type.toLowerCase())&&patterns.some(p=>x.code.toLowerCase()===p||x.code.toLowerCase().includes(p)))}
function findStatus(d:TuyaDevice,patterns:string[]){return d.status.find(x=>patterns.some(p=>x.code.toLowerCase()===p||x.code.toLowerCase().includes(p)))}
function deviceKind(d:TuyaDevice){const s=`${d.name} ${d.productName} ${d.category}`.toLowerCase();if(/air conditioner|klíma|climate|aircon/.test(s))return"climate";if(/temperature|humidity|hőmér|thermo|sensor/.test(s))return"sensor";if(/gate|kapu|garage|garázs|lock/.test(s))return"gate";if(/light|bulb|lamp|lámpa|rgb|cct/.test(s))return"light";if(/plug|socket|switch|outlet|konnektor/.test(s))return"switch";return"device"}
function metric(d:TuyaDevice,patterns:string[]){const p=findStatus(d,patterns);if(!p||typeof p.value!=="number")return null;const meta=specValues(d,p.code);const scale=Number(meta.scale||0);const v=p.value/Math.pow(10,scale);return{value:v,unit:String(meta.unit||""),scale}}
function batteryPercent(d:TuyaDevice){const codes=["battery_percentage","battery_percent","battery_pct","battery_value"];const p=d.status.find(x=>codes.includes(x.code.toLowerCase())&&typeof x.value==="number");if(!p)return null;const meta=specValues(d,p.code);const scale=Number(meta.scale||0);let v=Number(p.value)/Math.pow(10,scale);const max=Number(meta.max||100);if(max>100&&v>100)v=v/max*100;if(v<0||v>100)return null;return Math.round(v)}
function enumRange(d:TuyaDevice,code?:string){if(!code)return[] as string[];const m=specValues(d,code);return Array.isArray(m.range)?m.range.map(String):[]}
function labelKind(kind:string){return kind==="climate"?"Klíma":kind==="sensor"?"Szenzor":kind==="switch"?"Kapcsoló":kind==="light"?"Világítás":kind==="gate"?"Kapu":"Eszköz"}
async function api(path:string,init?:RequestInit){const r=await fetch(path,init);if(r.status===401)throw new Error("AUTH_REQUIRED");const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);return b}

function Login({onDone}:{onDone:()=>void}){const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});onDone()}catch(err){setError(err instanceof Error&&err.message==="too_many_attempts"?"Túl sok sikertelen próbálkozás. Próbáld később.":"Hibás jelszó.")}finally{setBusy(false)}}return <main className="loginShell"><section className="loginCard"><div className="brandMark">H</div><div className="eyebrow">HOME HUB</div><h1>Belépés</h1><p>NAS, hálózat és okosotthon egyetlen felületen.</p><form onSubmit={submit}><input type="password" autoFocus autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="HomeHub jelszó"/><button disabled={busy||!password}>{busy?"Belépés…":"Belépés"}</button></form>{error&&<div className="loginError">{error}</div>}</section></main>}

function SmartDeviceCard({device,onCommand}:{device:TuyaDevice;onCommand:(d:TuyaDevice,code:string,value:unknown)=>void}){
  const kind=deviceKind(device),sm=statusMap(device),battery=batteryPercent(device);
  const temp=(kind==="sensor"||kind==="climate")?metric(device,["temp_current","va_temperature","temperature","temp_value"]):null;
  const hum=(kind==="sensor"||kind==="climate")?metric(device,["humidity_value","va_humidity","humidity","humid"]):null;
  const switchFn=(kind==="switch"||kind==="light"||kind==="gate"||kind==="climate")?findFunction(device,["switch","switch_1","switch_led","power","power_switch"],"Boolean"):undefined;
  const switchCode=switchFn?.code;const switchValue=switchCode?Boolean(sm[switchCode]):undefined;
  const setTempFn=kind==="climate"?findFunction(device,["temp_set","target_temp","temp_target","temp_set_f"]):undefined;
  const modeFn=kind==="climate"?findFunction(device,["mode","work_mode"],"Enum"):undefined;
  const fanFn=kind==="climate"?findFunction(device,["fan_speed","windspeed","wind_speed","fan"],"Enum"):undefined;
  const setTempCode=setTempFn?.code,modeCode=modeFn?.code,fanCode=fanFn?.code;
  const [target,setTarget]=useState(()=>{if(!setTempCode)return"";const v=sm[setTempCode];const m=specValues(device,setTempCode);const scale=Number(m.scale||0);return typeof v==="number"?String(v/Math.pow(10,scale)):""});
  const modeRange=enumRange(device,modeCode),fanRange=enumRange(device,fanCode);
  const readOnly=device.status.filter(p=>typeof p.value==="string"||typeof p.value==="number"||typeof p.value==="boolean").slice(0,3);
  return <article className={`smartDevice ${kind}`}>
    <div className="deviceHead"><div><span className={`deviceDot ${device.online?"on":""}`}></span><strong>{device.name}</strong></div><span className="deviceKind">{labelKind(kind)}</span></div>
    <small>{device.productName||device.category||"Smart Life eszköz"} · {device.online?"Online":"Offline"}</small>
    <div className="metrics">{temp&&<span>🌡 {temp.value.toFixed(temp.scale>0?1:0)}{temp.unit?` ${temp.unit}`:" °C"}</span>}{hum&&<span>💧 {hum.value.toFixed(hum.scale>0?1:0)}{hum.unit?` ${hum.unit}`:" %"}</span>}{battery!==null&&<span>🔋 {battery}%</span>}</div>
    <div className="deviceControls">
      {switchCode&&<button className={switchValue?"power on":"power"} disabled={!device.online} onClick={()=>{if(isDangerous(device.name)&&!window.confirm(`${device.name}: biztosan végrehajtod?`))return;onCommand(device,switchCode,!switchValue)}}>{switchValue?"Kikapcsolás":"Bekapcsolás"}</button>}
      {setTempCode&&<div className="tempControl"><input type="number" step="0.5" value={target} onChange={e=>setTarget(e.target.value)}/><button disabled={!device.online||!target} onClick={()=>{const m=specValues(device,setTempCode);const scale=Number(m.scale||0);onCommand(device,setTempCode,Math.round(Number(target)*Math.pow(10,scale)))}}>Beállítás</button></div>}
      {modeCode&&modeRange.length>0&&<label className="selectControl">Mód<select value={String(sm[modeCode]??"")} disabled={!device.online} onChange={e=>onCommand(device,modeCode,e.target.value)}>{modeRange.map(m=><option value={m} key={m}>{m}</option>)}</select></label>}
      {fanCode&&fanRange.length>0&&<label className="selectControl">Ventilátor<select value={String(sm[fanCode]??"")} disabled={!device.online} onChange={e=>onCommand(device,fanCode,e.target.value)}>{fanRange.map(m=><option value={m} key={m}>{m}</option>)}</select></label>}
    </div>
    {kind==="device"&&readOnly.length>0&&<div className="rawMetrics">{readOnly.map(p=><span key={p.code}>{p.code}: {String(p.value)}</span>)}</div>}
  </article>
}

function DeleteDialog({torrent,onClose,onDelete}:{torrent:Torrent;onClose:()=>void;onDelete:(deleteData:boolean)=>void}){return <div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal"><span className="dangerMark">!</span><h2>Torrent törlése</h2><p><strong>{torrent.name}</strong></p><p>A WD My Cloudra már átmásolt példányhoz egyik művelet sem nyúl.</p><div className="modalActions"><button className="secondary" onClick={()=>onDelete(false)}>Csak torrent eltávolítása</button><button className="danger" onClick={()=>onDelete(true)}>Torrent + KD20 fájlok törlése</button><button className="ghost" onClick={onClose}>Mégse</button></div></section></div>}

function App(){
  const[auth,setAuth]=useState<"checking"|"yes"|"no">("checking"),[state,setState]=useState<State|null>(null),[magnet,setMagnet]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[deleteTarget,setDeleteTarget]=useState<Torrent|null>(null);
  async function checkAuth(){const r=await fetch("/api/auth/status");const j=await r.json();setAuth(j.authenticated?"yes":"no")}
  async function load(){try{setState(await api("/api/state"));setAuth("yes")}catch(err){if(err instanceof Error&&err.message==="AUTH_REQUIRED")setAuth("no")}}
  useEffect(()=>{checkAuth();if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{})},[]);
  useEffect(()=>{if(auth!=="yes")return;load();const id=setInterval(load,3000);return()=>clearInterval(id)},[auth]);
  const torrents=state?.snapshot?.kd20.torrents||[],printer=state?.snapshot?.printer,network=state?.snapshot?.network||[],smart:SmartHome=state?.smartHome??{configured:false,online:false,lastUpdatedAt:null,devices:[],scenes:[]};
  const totalDl=useMemo(()=>torrents.reduce((a,t)=>a+t.rateDownload,0),[torrents]),totalUl=useMemo(()=>torrents.reduce((a,t)=>a+t.rateUpload,0),[torrents]),wdUsed=state?.snapshot?.wd.totalBytes?1-state.snapshot.wd.freeBytes/state.snapshot.wd.totalBytes:0;
  function flash(m:string){setNotice(m);window.setTimeout(()=>setNotice(""),4000)}
  async function addMagnet(e:React.FormEvent){e.preventDefault();if(!magnet.trim())return;setBusy(true);try{await api("/api/torrents/magnet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({magnet})});setMagnet("");flash("Magnet link elküldve a KD20-nak.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}finally{setBusy(false);load()}}
  async function addFile(file?:File){if(!file)return;const fd=new FormData();fd.append("torrent",file);setBusy(true);try{await api("/api/torrents/file",{method:"POST",body:fd});flash(".torrent fájl elküldve a KD20-nak.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}finally{setBusy(false);load()}}
  async function copy(t:Torrent){try{await api(`/api/torrents/${t.id}/copy`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});flash("Másolási feladat elküldve.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}load()}
  async function retryCopy(hash:string){try{await api(`/api/copies/${encodeURIComponent(hash)}/retry`,{method:"POST"});flash("Másolás újrapróbálása elküldve.")}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}load()}
  async function removeTorrent(deleteData:boolean){if(!deleteTarget)return;const t=deleteTarget;setDeleteTarget(null);try{await api(`/api/torrents/${t.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({deleteData,confirm:true})});flash(deleteData?"Torrent és KD20 fájlok törlése elküldve. A WD másolat megmarad.":"Torrent eltávolítása elküldve. A KD20 fájlok megmaradnak.")}catch(err){flash(`Törlési hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}setTimeout(load,1000)}
  async function updateSettings(patch:Partial<State["settings"]>){if(!state)return;const next={...state.settings,...patch};try{await api("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});load()}catch(err){flash(`Hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function smartCommand(d:TuyaDevice,code:string,value:unknown){try{await api(`/api/smart-home/devices/${encodeURIComponent(d.id)}/command`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,value,confirm:isDangerous(d.name)})});flash(`${d.name}: parancs elküldve`);setTimeout(load,900)}catch(err){flash(`Smart Life hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function runScene(s:TuyaScene){const dangerous=isDangerous(s.name);if(dangerous&&!window.confirm(`${s.name}: biztosan elindítod ezt a jelenetet?`))return;try{await api(`/api/smart-home/scenes/${encodeURIComponent(s.id)}/run`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirm:dangerous})});flash(`${s.name}: jelenet elindítva`);setTimeout(load,700)}catch(err){flash(`Jelenet hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function refreshSmart(){try{await api("/api/smart-home/refresh",{method:"POST"});load();flash("Smart Life frissítve")}catch(err){flash(`Tuya hiba: ${err instanceof Error?err.message:"ismeretlen"}`)}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setState(null);setAuth("no")}
  if(auth==="checking")return<main className="splash"><div className="brandMark">H</div><p>HomeHub betöltése…</p></main>;if(auth==="no")return<Login onDone={()=>setAuth("yes")}/>;
  return <main>{notice&&<div className="toast">{notice}</div>}{deleteTarget&&<DeleteDialog torrent={deleteTarget} onClose={()=>setDeleteTarget(null)} onDelete={removeTorrent}/>}<header className="hero"><div><div className="eyebrow">HOME HUB · CORE</div><h1>Otthoni vezérlőközpont</h1><p>NAS, torrent, hálózat, nyomtató és Smart Life egyetlen PWA-ban.</p></div><div className="heroActions"><div className="live"><span className={state?.bridgeOnline?"dot on":"dot"}></span>{state?.bridgeOnline?"Bridge online":`Bridge offline · ${bridgeAge(state?.bridgeLastSeenAt)}`}</div><button className="ghost" onClick={logout}>Kilépés</button></div></header>

  <section className="cards four"><article className="card"><span>KD20</span><strong>{state?.bridgeOnline&&state?.snapshot?.kd20.online?"Online":"Offline"}</strong><small>{torrents.length} torrent · ↓ {fmtSpeed(totalDl)} · ↑ {fmtSpeed(totalUl)}</small></article><article className="card"><span>WD My Cloud</span><strong>{state?.bridgeOnline&&state?.snapshot?.wd.online?"Online":"Offline"}</strong><small>{state?.snapshot?`${fmtBytes(state.snapshot.wd.freeBytes)} szabad · ${Math.round(wdUsed*100)}% foglalt`:"Nincs adat"}</small></article><article className="card"><span>Hálózat</span><strong>{network.filter(n=>n.online).length}/{network.length||0} online</strong><small>Technicolor + Archer + TP-Link extenderek</small></article><article className="card"><span>Smart Life</span><strong>{smart.configured?(smart.online?"Online":"Hiba"):"Nincs konfigurálva"}</strong><small>{smart.devices.length} eszköz · {smart.scenes.length} jelenet</small></article></section>

  <section className="panel networkPanel"><div className="sectionHead"><div><h2>Otthoni hálózat</h2><p>Ping, ARP és admin-port ellenőrzés a WD Bridge-ről.</p></div></div><div className="networkGrid">{network.map(n=><article className="networkDevice" key={n.id}><div className="deviceHead"><div><span className={`deviceDot ${n.online?"on":""}`}></span><strong>{n.name}</strong></div><span className="deviceKind">{n.kind==="gateway"?"Telekom gateway":n.kind==="router"?"Router":"Wi-Fi erősítő"}</span></div><small>{n.ip||"IP keresése…"}{n.mac?` · ${n.mac}`:""}</small><div className="networkMeta"><span>{n.online?(n.latencyMs>0?`${n.latencyMs.toFixed(1)} ms`:"Jelen van"):"Nem elérhető"}</span>{n.adminUrl&&n.ip&&<a className={n.adminOnline===false?"mutedLink":""} href={n.adminUrl} target="_blank" rel="noreferrer">Admin{n.adminOnline===false?" (nem válaszol)":""}</a>}</div><em>{n.note}</em></article>)}{network.length===0&&<div className="empty">A Bridge még nem küldött hálózati adatot.</div>}</div><div className="infoLine">Az eszköz most már akkor is online lehet, ha a webadmin portja zárt: a Bridge pinget és ARP-jelenlétet is figyel.</div></section>

  <section className="panel smartPanel"><div className="sectionHead"><div><h2>Smart Life</h2><p>Tuya Central Europe Cloud · eszközök, klíma és Tap-to-Run jelenetek.</p></div><button className="ghost" onClick={refreshSmart}>Frissítés</button></div>{!smart.configured&&<div className="empty">Renderben add meg a TUYA_ACCESS_ID, TUYA_ACCESS_SECRET és TUYA_API_ENDPOINT változókat.</div>}{smart.configured&&!smart.online&&<div className="smartError">Tuya kapcsolat: {smart.error||"nem elérhető"}</div>}{smart.devices.length>0&&<div className="smartGrid">{smart.devices.map(d=><SmartDeviceCard key={d.id} device={d} onCommand={smartCommand}/>)}</div>}{smart.scenes.length>0&&<div className="scenes"><h3>Jelenetek</h3><div className="sceneGrid">{smart.scenes.map(s=><button className={isDangerous(s.name)?"scene danger":"scene"} key={`${s.homeId||"x"}-${s.id}`} disabled={s.enabled===false} onClick={()=>runScene(s)}>{s.name}{isDangerous(s.name)&&<small>Megerősítés szükséges</small>}</button>)}</div></div>}{smart.online&&smart.scenes.length===0&&<div className="infoLine">Nem érkezett jelenet. Ha a Smart Life-ban vannak Tap-to-Run jelenetek, ellenőrizd a Tuya projekt Scene Management jogosultságát.</div>}</section>

  <section className="panel add"><div><h2>Új torrent</h2><p>Magnet link vagy .torrent fájl.</p></div><form onSubmit={addMagnet} className="magnet"><input value={magnet} onChange={e=>setMagnet(e.target.value)} placeholder="magnet:?xt=urn:btih:…"/><button disabled={busy||!state?.bridgeOnline}>Hozzáadás</button></form><label className={`filebtn ${!state?.bridgeOnline?"disabled":""}`}>.torrent fájl<input disabled={!state?.bridgeOnline} type="file" accept=".torrent,application/x-bittorrent" onChange={e=>addFile(e.target.files?.[0])}/></label></section>

  <section className="panel"><div className="sectionHead"><div><h2>Torrentek</h2><p>A KD20 Transmission állapota, WD-re másolás és manuális törlés.</p></div><button className="ghost" onClick={load}>Frissítés</button></div><div className="torrentList">{torrents.length===0&&<div className="empty">Még nincs torrent, vagy a Bridge nem küldött adatot.</div>}{torrents.map(t=>{const cp=t.hashString?state?.copies?.[t.hashString]:undefined,copying=cp&&(cp.state==="queued"||cp.state==="running"),done=cp?.state==="done",copyPct=Math.max(0,Math.min(100,Math.round((cp?.percent||0)*100)));return <article className="torrent" key={t.hashString||t.id}><div className="torrentTop"><div><strong>{t.name}</strong><span>{Math.round(t.percentDone*100)}%</span><small className="torrentStatus">{statusLabel(t.status)}</small></div><div className="copyActions">{cp?.state==="error"&&<button className="retry" onClick={()=>retryCopy(t.hashString)}>Újrapróbálás</button>}<button onClick={()=>copy(t)} disabled={t.percentDone<1||!state?.bridgeOnline||Boolean(copying)||Boolean(done)}>{done?"Átmásolva":copying?"Másolás…":"Másolás WD-re"}</button><button className="deleteBtn" onClick={()=>setDeleteTarget(t)} disabled={!state?.bridgeOnline}>Törlés</button></div></div><div className="bar"><i style={{width:`${Math.max(1,t.percentDone*100)}%`}}></i></div><small>↓ {fmtSpeed(t.rateDownload)} · ↑ {fmtSpeed(t.rateUpload)} · ID {t.id}{t.eta>0&&t.eta<31536000?` · ETA ${fmtDuration(t.eta)}`:""}</small>{cp&&<div className={`copyState ${cp.state}`}><div className="copyStateLine"><span>Másolás: {cp.state==="queued"?"sorban":cp.state==="running"?"folyamatban":cp.state==="done"?`kész → ${cp.destination}`:`hiba${cp.message?` · ${cp.message}`:""}`}</span>{cp.state==="running"&&<b>{copyPct}%</b>}</div>{cp.state==="running"&&<><div className="copyBar"><i style={{width:`${Math.max(1,copyPct)}%`}}></i></div><div className="copyMeta"><span>{fmtBytes(cp.copiedBytes||0)} / {fmtBytes(cp.totalBytes||0)}</span><span>{fmtSpeed(cp.speedBytesPerSec||0)}</span><span>~ {fmtDuration(cp.etaSeconds)}</span></div>{cp.currentFile&&<div className="copyFile">{cp.currentFile}</div>}</>}</div>}</article>})}</div></section>

  <section className="panel printerPanel"><div><h2>USB nyomtatómegosztás</h2><p>A KD20 USB Print Server funkcióját használjuk.</p></div><div className="printerStatus"><span className={printer?.online?"statusBadge good":"statusBadge"}>{printer?.online?"Nyomtatószolgáltatás elérhető":"Nyomtató még nincs észlelve"}</span><small>{printer?.note||"A Bridge figyeli a nyomtatóportokat."}</small></div><div className="printerActions">{printer?.adminUrl&&<a className="actionLink" href={printer.adminUrl} target="_blank" rel="noreferrer">KD20 Printer Setting</a>}<span>USB → KD20 → Printer Setting → Enable.</span></div></section>
  <section className="panel settings"><div><h2>Automatika</h2><p>A kész torrentet WD-re másolja, a KD20-on seedeléshez megőrzi. A beállítás a WD-n is tartósan mentődik.</p></div><label className="switch"><input type="checkbox" checked={state?.settings.autoCopyEnabled||false} onChange={e=>updateSettings({autoCopyEnabled:e.target.checked})}/><span></span> Automatikus másolás</label><label>Célmappa a WD-n<input value={state?.settings.autoCopyDestination||""} onChange={e=>setState(s=>s?({...s,settings:{...s.settings,autoCopyDestination:e.target.value}}):s)} onBlur={e=>updateSettings({autoCopyDestination:e.target.value})}/></label></section>
  </main>
}
createRoot(document.getElementById("root")!).render(<App/>);
